# **Our First Project**

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
csv_path = next(Path("/kaggle/input").rglob("StudentPerformanceFactors.csv"))
df = pd.read_csv(csv_path)
df.head(10)
print(df.shape)
print(df.describe)
df.info()

(6607, 20)
<bound method NDFrame.describe of       Hours_Studied  Attendance Parental_Involvement Access_to_Resources  \
0                23          84                  Low                High
1                19          64                  Low              Medium
2                24          98               Medium              Medium
3                29          89                  Low              Medium
4                19          92               Medium              Medium
...             ...         ...                  ...                 ...
6602             25          69                 High              Medium
6603             23          76                 High              Medium
6604             20          90               Medium                 Low
6605             10          86                 High                High
6606             15          67               Medium                 Low

     Extracurricular_Activities  Sleep_Hours  Previous_Scores  \
0                            No            7               73
1                            No            8               59
2                           Yes            7               91
3                           Yes            8               98
4                           Yes            6               65
...                         ...          ...              ...
6602                         No            7               76
6603                         No            8               81
6604                        Yes            6               65
6605                        Yes            6               91
6606                        Yes            9               94

     Motivation_Level Internet_Access  Tutoring_Sessions Family_Income  \
0                 Low             Yes                  0           Low
1                 Low             Yes                  2        Medium
2              Medium             Yes                  2        Medium
3              Medium             Yes                  1        Medium
4              Medium             Yes                  3        Medium
...               ...             ...                ...           ...
6602           Medium             Yes                  1          High
6603           Medium             Yes                  3           Low
6604              Low             Yes                  3           Low
6605             High             Yes                  2           Low
6606           Medium             Yes                  0        Medium

     Teacher_Quality School_Type Peer_Influence  Physical_Activity  \
0             Medium      Public       Positive                  3
1             Medium      Public       Negative                  4
2             Medium      Public        Neutral                  4
3             Medium      Public       Negative                  4
4               High      Public        Neutral                  4
...              ...         ...            ...                ...
6602          Medium      Public       Positive                  2
6603            High      Public       Positive                  2
6604          Medium      Public       Negative                  2
6605          Medium     Private       Positive                  3
6606          Medium      Public       Positive                  4

     Learning_Disabilities Parental_Education_Level Distance_from_Home  \
0                       No              High School               Near
1                       No                  College           Moderate
2                       No             Postgraduate               Near
3                       No              High School           Moderate
4                       No                  College               Near
...                    ...                      ...                ...
6602                    No              High School               Near
6603                    No              High School               Near
6604                    No             Postgraduate               Near
6605                    No              High School                Far
6606                    No             Postgraduate               Near

      Gender  Exam_Score
0       Male          67
1     Female          61
2       Male          74
3       Male          71
4     Female          70
...      ...         ...
6602  Female          68
6603  Female          69
6604  Female          68
6605  Female          68
6606    Male          64

[6607 rows x 20 columns]>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6517 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), object(13)
memory usage: 1.0+ MB

In [3]:
print(df.isna().sum())

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

In [4]:
df.describe()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6607.000000,6607.000000,6607.00000,6607.000000,6607.000000,6607.000000,6607.000000
mean,19.975329,79.977448,7.02906,75.070531,1.493719,2.967610,67.235659
std,5.990594,11.547475,1.46812,14.399784,1.230570,1.031231,3.890456
min,1.000000,60.000000,4.00000,50.000000,0.000000,0.000000,55.000000
25%,16.000000,70.000000,6.00000,63.000000,1.000000,2.000000,65.000000
50%,20.000000,80.000000,7.00000,75.000000,1.000000,3.000000,67.000000
75%,24.000000,90.000000,8.00000,88.000000,2.000000,4.000000,69.000000
max,44.000000,100.000000,10.00000,100.000000,8.000000,6.000000,101.000000

In [5]:
print(df.duplicated().sum())

0

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
x = df[["Hours_Studied"]]
y = df[["Exam_Score"]]

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.30,random_state = 12)

In [10]:
x_train

      Hours_Studied
2098             11
4125             13
1371             30
2872              7
1116             34
...             ...
3714             26
3325             23
1414             16
5787             32
5963             12

[4624 rows x 1 columns]

In [11]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [12]:
y_pred = model.predict(x_test)
y_pred

array([[65.77724846],
       [65.48841916],
       [70.10968795],
       ...,
       [69.24320005],
       [72.42032235],
       [66.35490706]])